### ISSUE TITLE
Translations file?

### ISSUE THREAD

**Issue by JoshuaDoshua** [javisperez/vuetranslate#1]
Hello! Thanks for sharing!!

Is it possible to store all translations in a single file and use v-translate globally?

i.e. I'm using Vuex to keep track of a dynamic language shifter and wondering what the best way to implement is. Any thoughts welcome!

**Comment by javisperez** [comment]
Hey @JoshuaDoshua thank you for opening an issue! And yeah, that's a functionality i was thinking in adding, so i'll be working on it and let you know when is done :) hopefully, would be this weekend.

About your need, i dont have plenty experience with Vuex but as i see it you could just use 

```
this.$translate.setLang('english')
```

or something when you receive a language shift notification via the Vuex store, but as i said, i have no experience with Vuex so i might be wrong.

If you give it a try just let me know please if you find any trouble and i'll try to help you, anyhow i'll add the functionality to dynamically load a single translation file. Good day!

**Comment by javisperez** [comment]
I've made the change, is in the 1.2.0 release here: https://github.com/javisperez/vuetranslate/releases/tag/1.2.0 as i understand your need, you can now load the translations globally with something like:

```
import MyLocales from 'locales';

Vue.use(VueTranslate);

Vue.locales(MyLocales);
```

and after that everything should be normally usable.

I've also updated a little the README text, explaining some methods and events you could probably use. If you do give it a try please let me know if you got it to work.
