### ISSUE TITLE
this.$translate.textWithParams is returning the translation string

### ISSUE THREAD

**Issue by glenngijsberts** [javisperez/vuetranslate#10]
Last week I've created the PR with the new method `this.$translate.textWithParams`. Since I'm using it now in a app I've came to the conclussion that it's not working since it's returning the translation string instead of a message with replacements.

I'll dig into it asap.

**Comment by pooledge** [comment]
It doesn't for me either.

`{{ tWithParams('Collapse filter section', {sectionTitle: 'tralala'}) }}`
using
```
Vue.locales({
	de: {
		'Expand filter section': 'Filter %sectionTitle% aufklappen',
	}
});
```
renders as `Filter %sectionTitle% aufklappen`

**Comment by glenngijsberts** [comment]
@pooledge exactly. Feel free to dive in, I'm a bit busy but I would like dive in somewhere in the upcoming days.

**Comment by javisperez** [comment]
Hey guys, sorry for the delay, this PR should fix it and is now merged and deployed. https://github.com/javisperez/vuetranslate/pull/11 Thanks for the issue and help!
