### ISSUE TITLE
Not obvious way to localize attributes (like placeholder)

### ISSUE THREAD

**Issue by arielsbecker** [javisperez/vuetranslate#13]
I'm trying hard to guess how to localize attributes, like `placeholder` inside an `<input>` tag. Tried several ways, but still had no luck.

Is there a trick I'm not aware of? If so, can you add it to the docs, so newbies like me can figure this out? Thanks!

**Comment by tobias-grasse** [comment]
Hope it's still relevant for you:
```html
<input type="text" :placeholder="t('some translatable string')" />
```

Mind the single quotes around the translatable text, otherwise you'll clobber the actual attribute quotes.

**Comment by arielsbecker** [comment]
> Hope it's still relevant for you:
> 
> ```
> <input type="text" :placeholder="t('some translatable string')" />
> ```
> 
> Mind the single quotes around the translatable text, otherwise you'll clobber the actual attribute quotes.

Hi! Sorry for the late reply. It worked; however, now it raised another question: how should I work with it if the input has a v-model statement?

This is what I have right now:

`<input class="something" type:"search" :placeholder="t('localizableString')" />`

So far, I achieved localization on the placeholder, but now the search function doesn't work anymore.

To clarify: the above code is the template; in the .vue component, it replaces the following:

`<span id="buscador" v-model=search></span>`

When I write something on that searchbox, an event is fired as intended, but it gets an empty string instead of the contents of the inputbox. How can I fix this without having to resort to a fixed placeholder?

**Comment by tobias-grasse** [comment]
I assume you want to output the current search string inside the `span` element? For that, I built a quick reproduction at https://codesandbox.io/s/vue-template-7tqq6?fontsize=14 which works just  with placeholder translation and v-model binding. If that's what you want to do, it seems to me that you have misread the docs for `v-model`.

```html
<!-- inside Vue component template section -->
<input type="search" :placeholder="t('localizableString')" v-model="search">
<span id="buscador">{{ search }}</span>
``
