### ISSUE TITLE
'params' is a local function variable, isn't it?

### ISSUE THREAD

**Issue by marcohofmann** [javisperez/vuetranslate#14]
https://github.com/javisperez/vuetranslate/blob/170d5ff5eeb28b60dfc9265fe8fbc27ecb8fa5de/src/vue-translate.js#L83

**Comment by jeremy-rafflin** [comment]
And this function is wrong I think : 
tWithParams: function (t, params) {
                return this.$translate.text(t, params);
            }

the correct function is not ? 
tWithParams: function (t, params) {
                return this.$translate.textWithParams(t, params);
            }

**Comment by javisperez** [comment]
https://github.com/javisperez/vuetranslate/pull/19 was merged which should fix this, thanks for the issue. Closing this now, thanks!
