### ISSUE TITLE
tWithParams calls text()

### ISSUE THREAD

**Issue by BananaAcid** [javisperez/vuetranslate#15]
https://github.com/javisperez/vuetranslate/blob/master/src/vue-translate.js#L112

should read textWithparams

**Comment by BananaAcid** [comment]
would be fixed in pull request https://github.com/javisperez/vuetranslate/pull/19

**Comment by javisperez** [comment]
Thanks for the PR! and sorry for the late response, I've been crazy busy, just merged and again, thank you!
