### ISSUE TITLE
this.params must be params

### ISSUE THREAD

**Issue by BananaAcid** [javisperez/vuetranslate#16]
https://github.com/javisperez/vuetranslate/blob/master/src/vue-translate.js#L83

resulting in dists error on [same line](https://github.com/javisperez/vuetranslate/blob/master/dist/vue-translate.common.js#L97)

you are referencing outside (this) `params` [ == undefined], not local scope `params`.

**Comment by BananaAcid** [comment]
would be fixed in pull request https://github.com/javisperez/vuetranslate/pull/19

**Comment by javisperez** [comment]
https://github.com/javisperez/vuetranslate/pull/19 was merged. Closing this now, thanks!
