### ISSUE TITLE
Vue.t should refer to textWithParams

### ISSUE THREAD

**Issue by BananaAcid** [javisperez/vuetranslate#17]
having `Vue.t()` to point to `$translate.text()` is unnecessary, pointing it to `$translate.textWithParams()` yields the same effect, since you if-out on missing params anyways. Someone wanting clear method names, would use `$translate,textWithParams()` anyways.

**Comment by BananaAcid** [comment]
would be fixed in pull request https://github.com/javisperez/vuetranslate/pull/19

**Comment by javisperez** [comment]
https://github.com/javisperez/vuetranslate/pull/19 was merged. Closing this now, thanks!
