### ISSUE TITLE
Sould not exit textWithParams if locale is not available

### ISSUE THREAD

**Issue by BananaAcid** [javisperez/vuetranslate#18]
https://github.com/javisperez/vuetranslate/blob/master/src/vue-translate.js#L79

Since the input string is used anyways, (`return t`) the code should not leave, but take `t` and do the replacing anyways.

**Comment by BananaAcid** [comment]
fixed in https://github.com/javisperez/vuetranslate/pull/19

**Comment by javisperez** [comment]
https://github.com/javisperez/vuetranslate/pull/19 is now merged, thanks for the PR! closing this now.
