### ISSUE TITLE
Getting text from globally translation file set

### ISSUE THREAD

**Issue by LeonardoSSev** [javisperez/vuetranslate#5]
I have a file that loads the translation plugin as it's set on the example:
```
Vue.use(VueTranslate);

Vue.locales({
	spanish: {
		'hello-world': 'hola mundo'
	}
        pt-br: {
                'hello-wolrd': Olá mundo
});
```
But I how do I get the hello-world in pt-br translation, for example?

I tried something like `this.$translate.text('hello-world')` on my script but it just appear `hello-world` instead of 'hola mundo` or `Olá mundo` when it's set as pt-br.

**Comment by tonn-talvik** [comment]
Isn't there a typo? **wolrd**

**Comment by javisperez** [comment]
@LeonardoSSev Thanks for the issue. As @tonn-talvik says, you have a typo there, please confirm if that fixes it. Thanks!

**Comment by LeonardoSSev** [comment]
Thanks for that observation, @tonn-talvik and @javisperez . Although I had written wrongly, the problem wasn't solved after I fixed the typo.
But I got the answer for what I needed. The translated string can be got through `this.t('hello-world');` inside <script> tags.
