### ISSUE TITLE
Use in variable

### ISSUE THREAD

**Issue by TheoLecoq** [javisperez/vuetranslate#8]
Is is possible to use the translation in a variable? Something like `$('#error').text( {{ t('error min max') }} );` ?

**Comment by tobias-grasse** [comment]
If I understand your question correctly: Yes, you can use vue-translate outside the template section, you just have to call `this.$translate.text("my text")` instead. In your example:

```js
$('#error').text(this.$translate.text("error min max"));
```

Make sure that the `this` context refers to the Vue instance where you define the locales.

**Comment by javisperez** [comment]
Hey, sorry for the looong delay 😅 but yeah @tobias-grasse is right! you can use it in your script part of the component. Please let us know if you have more questions, thanks.
